In [73]:
import os
import re
import cv2
import numpy as np
import pickle

import argus
from argus import Model
from argus import load_model

In [83]:
small_dict = {}
for i, name in enumerate(os.listdir('/workdir/data/datasets/ships_small/train_small/images/')):
    small_dict[name.split('.')[0]] = i//3

In [84]:
small_dict

{'000303d4d': 0,
 '0002d0f32': 0,
 '00003e153': 0,
 '000155de5': 1,
 '00021ddc3': 1,
 '0002756f7': 1}

In [90]:
small_dict = {   
                 '000155de5': 0,
                 '00021ddc3': 1,
                 '0002756f7': 2}

In [88]:
small_dict = {'000303d4d': 0,
 '0002d0f32': 1,
 '00003e153': 2,
 '000155de5': 0,
 '00021ddc3': 1,
 '0002756f7': 2}

In [91]:
with open('/workdir/data/datasets/kfolds_small.pk', 'wb') as handle:
    pickle.dump(small_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [68]:
with open('/workdir/data/datasets/kfolds.pk', 'rb') as handle:
    folds_dict = pickle.load(handle)

In [69]:
folds_dict

{'000155de5': 0,
 '32018f9a6': 0,
 '9aa2690f2': 0,
 '340226019': 0,
 '82656c85f': 0,
 '07ae92b4f': 0,
 'a6a84cc21': 0,
 '9caee815e': 0,
 'b2e52ebf8': 0,
 'f86c72243': 1,
 'd3d5edcf0': 4,
 '285c29528': 0,
 'cf94376c1': 0,
 '384765ab2': 0,
 '000194a2d': 0,
 '23d9ae03d': 4,
 '2aa9901a8': 4,
 '0efbf3431': 0,
 'f3cd16e96': 0,
 '00021ddc3': 0,
 '44121e9df': 0,
 'f823d6e56': 0,
 '51963e563': 0,
 '0002756f7': 0,
 '03b25afe0': 0,
 'd177850d9': 0,
 '2251c909f': 0,
 '992063b98': 0,
 'dac54e322': 0,
 '4351227f6': 0,
 '00031f145': 0,
 'a6f4088f8': 0,
 'f34b21c70': 0,
 'ce0f3a682': 0,
 '46e210ec2': 0,
 'db5961f51': 0,
 '580f12152': 0,
 'f216d616c': 0,
 '000532683': 0,
 'f93f6e230': 0,
 '900bd2a91': 0,
 '7a043fbeb': 0,
 '1f5ecd434': 1,
 '5b64ea65c': 0,
 '66faa61ab': 0,
 '3bca4b0db': 3,
 'a92a7a724': 3,
 '651119560': 3,
 '7953c7337': 3,
 '1061ac111': 1,
 '4065b93a0': 0,
 '1c4a67c4e': 2,
 '00053c6ba': 0,
 'e1af54017': 2,
 '71a85d02a': 2,
 '6a62543d2': 0,
 '679ce6001': 0,
 '82d6b5662': 0,
 '232ddfc66': 

In [28]:
trg = np.zeros((10,10))

In [29]:
trg[5:7,3:5] = 255

In [30]:
trg[5,3] = 254

In [31]:
trg

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 254., 255.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 255., 255.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [33]:
mask = np.float32(trg > 0)
mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [34]:
unique = np.unique(trg)
unique

array([  0., 254., 255.])

In [39]:
mask_op = np.pad(mask, ((1, 1), (1, 1)), mode='constant')
mask_op

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [42]:
boundaries = np.zeros_like(mask_op, dtype=np.uint8)  # Hope, 255 ships is the max on an image
boundaries

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [45]:
distance = np.zeros_like(mask_op, dtype=np.float32)
distance

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
for i in unique[1:]:
    ship = np.uint8(trg == i)
    ship = np.pad(ship, ((1, 1), (1, 1)), mode='constant')
    # Boundaries
    dilation = cv2.dilate(ship, self.kernel, iterations=1)
    erosion = cv2.erode(ship, self.kernel, iterations=1)
    boundary = dilation - erosion
    boundaries += boundary.copy()

    # Distance transform
    dt = cv2.distanceTransform(ship, distanceType=cv2.DIST_L2, maskSize=5)
    cv2.normalize(dt, dt, 0, 1.0, cv2.NORM_MINMAX)
    distance += dt

In [46]:
unique[1:]

array([254., 255.])

In [48]:
np.uint8(trg == 254)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [50]:
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))

In [63]:
mask_op[3:8,1:6] = 1

In [64]:
mask_op

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [65]:
cv2.erode(mask_op, kernel, iterations=1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
mask = np.float32(mask > 0)
unique = np.unique(trg)